[project]
name = "hw-workshop2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "ipywidgets>=8.1.7",
    "notebook>=7.4.4",
    "openai>=1.95.1",
    "python-dotenv>=1.1.1",
]
